name: 'Choreo Workflow Logger'
description: 'Send Github Action Workflow logs to Azure Logs Analytics'
author: 'WSO2'
inputs:
  domain:
    required: true
    description: "Choreo Domain"
  component-id:
    required: true
    description: "Choreo component Id"
  run-id:
    required: true
    description: "Run ID of the workflow"
  secret:
    required: true
    description: "Secret code for the webhook"
  sha:
    required: true
    description: "Commit sha"
runs:
  using: 'node16'
  main: 'index.js'